<%@ Page Title="Your Cart" MasterPageFile="~/Site.Master" Language="C#" AutoEventWireup="true" CodeBehind="CustomerCart.aspx.cs" Inherits="BookstoreProject.Webpages.CustomerCart" %>

<asp:Content ID="CartContent" ContentPlaceHolderID="MainContent" runat="server">
    
    <h3>Your Cart</h3>

     
    <div align="Right">
        <asp:Button ID="btnOrderAll" runat="server" Text="Order All" width="100" OnClick="btnOrderAll_Click"/>

    </div>

    <div>
        <asp:GridView ID="gvwCartItems" runat="server" CellSpacing="2" Width="100%" GridLines="None" AutoGenerateDeleteButton="True" OnRowDeleting="RemoveItem">
            <AlternatingRowStyle BackColor="#F0F0F0" />
        </asp:GridView>
    </div>
    <div>

        <asp:Label ID="lblTotal" runat="server"></asp:Label>

    </div>

</asp:Content>
