<%@ Page Title="View Records" MasterPageFile="~/Site.Master" Language="C#" AutoEventWireup="true" CodeBehind="RecordsView.aspx.cs" Inherits="BookstoreProject.Webpages.RecordsView" %>

<asp:Content ID="RecordsViewContent" ContentPlaceHolderID="MainContent" runat="server">
    
    <h3>Browse Records - (Admin Only)</h3>

    <div>
        <asp:Label ID="lblCategory" runat="server" Text="Select a search category: " Font-Size="10"></asp:Label>
        <asp:DropDownList ID="ddlCategory" runat="server" Font-Size="10" OnSelectedIndexChanged="categoryChange" AutoPostBack="true">
            <asp:ListItem Selected="true" Value="Books"> Books </asp:ListItem>
            <asp:ListItem Selected="false" Value="Authors"> Authors </asp:ListItem>
            <asp:ListItem Selected="false" Value="Suppliers"> Suppliers </asp:ListItem>
            <asp:ListItem Selected="false" Value="Customers"> Customers </asp:ListItem>
            <asp:ListItem Selected="false" Value="Orders"> Orders </asp:ListItem>

        </asp:DropDownList>

    </div>

    <asp:Table ID="tblSearchData" runat="server">
         <asp:TableRow>
             <asp:TableCell>
                 <asp:Label ID="lblF1" runat="server" Text="Title:" Font-Size="10" Width="100"></asp:Label>
                 <asp:TextBox ID="tbxF1" runat="server" Font-Size="10"></asp:TextBox>
             </asp:TableCell>
         </asp:TableRow>

        <asp:TableRow>
             <asp:TableCell>
                 <asp:Label ID="lblF2" runat="server" Text="Author:" Font-Size="10" Width="100"></asp:Label>
                 <asp:TextBox ID="tbxF2" runat="server" Font-Size="10"></asp:TextBox>
             </asp:TableCell>
        </asp:TableRow>

        <asp:TableRow>
             <asp:TableCell>
                 <asp:Label ID="lblF3" runat="server" Text="Supplier:" Font-Size="10" Width="100"></asp:Label>
                 <asp:TextBox ID="tbxF3" runat="server" Font-Size="10"></asp:TextBox>
             </asp:TableCell>
        </asp:TableRow>
     </asp:Table>
    


    <div align="Right">
        <asp:Button ID="btnRefreshTable" runat="server" Text="Search" OnClick="btnRefresh" width="100"/>
        <asp:Button ID="btnResetFilters" runat="server" Text="Reset" OnClick="btnClearFilters" width="100"/>

    </div>

    <div>
        <asp:Button ID="btnInsert" runat="server" OnClick="btnInsert_Click" Text="Add New" />
        <asp:GridView ID="gvwData" runat="server" CellSpacing="2" Width="100%" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="Row_CancelEdit" OnRowDeleting="Row_Deleting" OnRowEditing="Row_Editing">
            <AlternatingRowStyle BackColor="#F0F0F0" />
        </asp:GridView>
    </div>



</asp:Content>
